apiVersion: v1
kind: Service
metadata:
  name: live-translate-service
  labels:
    app: live-translate
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: live-translate
